### ISSUE TITLE
Unable to build refmt.js

### ISSUE THREAD

**Issue by glennsl** [facebook/reason#1807]
Able to build reason on 4.04.2, but unable to do so on 4.02.3. But first, just to get to the point of trying to build reason I had to:

* install merlin-extend and utop into the 4.02.3 switch (I also think I had to install utop on 4.04.2, which wasn't mentoned in the build instructions)
* change `js_of_ocaml.exe` to `js_of_ocaml` in `bspacks/reason_bspack.sh`

This is the log from running `reason_bspack.sh`:

```
**This script is switching you to ocaml 4.02.3 for the subsequent bspacking. Please switch back to your own version afterward. Thanks!**\n
# To setup the new switch in the current shell, you need to run:
eval `opam config env`
~/dev/remote/_/reason/bspacks ~/dev/remote/_/reason/bspacks
make: Entering directory '/home/glennsl/dev/remote/_/reason'
rm -rf ./formatTest/**/actual_output
rm -f ./formatTest/failed_tests
rm -f ./miscTests/reactjs_jsx_ppx_tests/*.cm*
jbuilder clean
make: Leaving directory '/home/glennsl/dev/remote/_/reason'
make: Entering directory '/home/glennsl/dev/remote/_/reason'
jbuilder build
    ocamldep src/reason-merlin/ocamlmerlin_reason.depends.ocamldep-output
    ocamldep src/ppx/ppx_react.depends.ocamldep-output
    ocamldep src/refmt/refmt_impl.depends.ocamldep-output
    ocamldep src/refmttype/reason_format_type.depends.ocamldep-output
    ocamldep src/reason-parser-tests/testOprint.depends.ocamldep-output
    ocamldep src/reason-parser/vendor/easy_format/reason.easy_format.dependsi.ocamldep-output
    ocamldep src/reason-parser/vendor/easy_format/reason.easy_format.depends.ocamldep-output
    ocamldep src/generate/select.depends.ocamldep-output
    ocamllex src/reason-parser/reason_lexer.ml
    ocamldep src/reason-parser/menhir_error_processor.depends.ocamldep-output
    ocamldep src/rtop/rtop.depends.ocamldep-output
    ocamldep src/ppx/ppx_react.dependsi.ocamldep-output
    ocamldep src/reason-parser/vendor/cmdliner/reason.cmdliner.dependsi.ocamldep-output
    ocamldep src/reason-parser/vendor/cmdliner/reason.cmdliner.depends.ocamldep-output
      ocamlc src/reason-parser/vendor/easy_format/easy_format.{cmi,cmti}
      ocamlc src/generate/select.{cmi,cmo,cmt}
      ocamlc src/reason-parser/menhir_error_processor.{cmi,cmo,cmt}
      ocamlc src/reason-parser/vendor/cmdliner/cmdliner.{cmi,cmti}
      ocamlc src/reason-parser/vendor/easy_format/easy_format.{cmo,cmt}
    ocamlopt src/generate/select.{cmx,o}
    ocamlopt src/reason-parser/vendor/easy_format/easy_format.{cmx,o}
    ocamlopt src/reason-parser/menhir_error_processor.{cmx,o}
      ocamlc src/reason-parser/vendor/easy_format/reason.easy_format.cma
  ocamlbuild src/reasonbuild/myocamlbuild
/home/glennsl/.opam/4.02.3/bin/ocamlopt.opt unix.cmxa -I /home/glennsl/.opam/4.02.3/lib/ocaml/ocamlbuild /home/glennsl/.opam/4.02.3/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/glennsl/.opam/4.02.3/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
    ocamlopt src/generate/select.exe
        bash src/reason-parser/reason_parser.messages (exit 1)
(cd _build/default/src/reason-parser && /usr/bin/bash -e -u -o pipefail -c 'menhir --explain --strict --unused-tokens ./reason_parser.mly --update-errors ./reason_parser.messages.checked-in | sed -e '\''s/[[:space:]]*$$//g'\''') > _build/default/src/reason-parser/reason_parser.messages
File "/home/glennsl/.opam/4.02.3/lib/menhir/standard.mly", line 193, characters 8-21:
Error: symbol nonempty_list(attribute) is unreachable from any of the start symbol(s).
make: *** [Makefile:8: build] Error 1
make: Leaving directory '/home/glennsl/dev/remote/_/reason'
File "src/reason-parser/reason_lexer.mll", line 70, characters 5-18:
Error: Unbound module Reason_parser
File "src/reason-parser/reason_lexer.mll", line 70, characters 5-18:
Error: Unbound module Reason_parser
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/glennsl/.opam/4.02.3/lib/ocaml, /home/glennsl/.opam/4.02.3/lib/ocaml/compiler-libs
File "./refmtJsApi.ml", line 1, characters 12-41:
Error: Unbound module Refmt_api
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/glennsl/.opam/4.02.3/lib/ocaml, /home/glennsl/.opam/4.02.3/lib/ocaml/compiler-libs
File "_none_", line 1:
Error: Cannot find file /home/glennsl/dev/remote/_/reason/bspacks/build/refmt_api_entry.cmo
js_of_ocaml: Error: Sys_error("/home/glennsl/dev/remote/_/reason/bspacks/build/refmt_api_final.byte: No such file or directory")
ERROR - Cannot read file /home/glennsl/dev/remote/_/reason/bspacks/build/refmt_pre_closure.js: {1}

1 error(s), 0 warning(s)
./reason_bspack.sh: line 105: /home/glennsl/dev/remote/_/reason/bspacks/build/refmt_binary.byte: No such file or directory
{}
/home/glennsl/dev/remote/_/reason/bspacks/testRefmtJs.js:4
console.log(refmt.printRE(refmt.parseRE(`let f = (a) => a + 1; print_int(f(5))`)))
                                ^

TypeError: refmt.parseRE is not a function
    at Object.<anonymous> (/home/glennsl/dev/remote/_/reason/bspacks/testRefmtJs.js:4:33)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

```sh
▶ uname -a
Linux **** 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux
```

**Comment by chenglou** [comment]
Seems like a menhir version problem. I'll check what I have tomorrow
