### ISSUE TITLE
Installation Permission Issues

### ISSUE THREAD

**Issue by kfish610** [facebook/reason#1900]
I have a similar issue to issue #1730. When I run `npm install -g reason-cli@3.1.0-linux`, this is the output:
```
/usr/bin/ocamlmerlin -> /usr/lib/node_modules/reason-cli/.bin/ocamlmerlin
/usr/bin/rtop -> /usr/lib/node_modules/reason-cli/.bin/rtop
/usr/bin/utop -> /usr/lib/node_modules/reason-cli/.bin/utop
/usr/bin/ocamlmerlin-reason -> /usr/lib/node_modules/reason-cli/.bin/ocamlmerlin-reason
/usr/bin/refmt -> /usr/lib/node_modules/reason-cli/.bin/refmt
/usr/bin/refmttype -> /usr/lib/node_modules/reason-cli/.bin/refmttype
/usr/bin/reopt -> /usr/lib/node_modules/reason-cli/.bin/reopt
/usr/bin/rebuild -> /usr/lib/node_modules/reason-cli/.bin/rebuild
/usr/bin/reactjs_jsx_ppx_v2 -> /usr/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_v2
/usr/bin/reactjs_jsx_ppx_v3 -> /usr/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_v3
/usr/bin/reason-cli-esy-sandbox -> /usr/lib/node_modules/reason-cli/.bin/reason-cli-esy-sandbox

> reason-cli@3.1.0-linux postinstall /usr/lib/node_modules/reason-cli
> ./bin/esyBuildRelease bin install

tar: r: Cannot mkdir: Permission denied
tar: r: Cannot mkdir: Permission denied
tar: r/node_modules: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/node_modules/.cache: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/node_modules/.cache/_esy: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/node_modules/.cache/_esy/store: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/node_modules/.cache/_esy/store/i: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/node_modules/.cache/_esy/store/b: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/node_modules/.cache/_esy/store/s: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/LICENSE: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/ORIGINS.md: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/yarn.lock: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/README.md: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/.travis.yml: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/esy.lock: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/Makefile: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/.npmignore: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/ocaml: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/ocaml/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/ocaml/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/merlin-extend: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/merlin-extend/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/merlin-extend/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/utop: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/utop/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/utop/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/cppo: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/cppo/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/cppo/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ppx_tools_versioned: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ppx_tools_versioned/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ppx_tools_versioned/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/biniou: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/biniou/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/biniou/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/camomile: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/camomile/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/camomile/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/base-unix: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/base-unix/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/base-unix/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/jbuilder: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/jbuilder/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/jbuilder/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/menhir: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/menhir/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/menhir/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/lwt: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/lwt/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/lwt/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/easy-format: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/easy-format/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/easy-format/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/result: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/result/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/result/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/conf-m4: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/conf-m4/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/conf-m4/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/react: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/react/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/react/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/lwt_react: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/lwt_react/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/lwt_react/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ocamlfind: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ocamlfind/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ocamlfind/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/conf-which: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/conf-which/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/conf-which/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/topkg: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/topkg/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/topkg/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/zed: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/zed/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/zed/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/lambda-term: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/lambda-term/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/lambda-term/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/camlp4: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/camlp4/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/camlp4/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/base-bytes: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/base-bytes/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/base-bytes/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ocaml-migrate-parsetree: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ocaml-migrate-parsetree/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ocaml-migrate-parsetree/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ocamlbuild: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ocamlbuild/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/ocamlbuild/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/base-threads: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/base-threads/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/base-threads/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/yojson: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/yojson/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@opam/yojson/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/esy-installer: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/esy-installer/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/esy-installer/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/reason: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/reason/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/reason/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/substs: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/substs/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/substs/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rtop: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rtop/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rtop/node_modules: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rtop/node_modules/@opam: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rtop/node_modules/@opam/result: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rtop/node_modules/@opam/result/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rtop/node_modules/@opam/result/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rtop/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/merlin: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/merlin/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/merlin/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rebuild: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rebuild/eject-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/node_modules/@esy-ocaml/rebuild/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin: Cannot mkdir: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin/shell-builder.sh: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin/esyExportBuild: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin/fastreplacestring.cpp: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin/get-store-path: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin/realpath.sh: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin/esyRuntime.sh: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin/esyImportBuild: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin/render-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin/realpath.c: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/bin/esyConfig.sh: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/Makefile: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/sandbox.sb.in: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/build-eject/sandbox-env: Cannot open: No such file or directory
tar: r: Cannot mkdir: Permission denied
tar: r/package.json: Cannot open: No such file or directory
tar: Exiting with failure status due to previous errors
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! reason-cli@3.1.0-linux postinstall: `./bin/esyBuildRelease bin install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the reason-cli@3.1.0-linux postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-15T22_53_07_478Z-debug.log
```

In the log file is:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'reason-cli@3.1.0-linux' ]
2 info using npm@5.8.0
3 info using node@v8.11.0
4 verbose npm-session 51d11e570deba7dd
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/reason-cli 197ms (from cache)
8 silly pacote version manifest for reason-cli@3.1.0-linux fetched in 214ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule reason-cli@3.1.0-linux checking installable status
14 silly currentTree lib
15 silly idealTree lib
15 silly idealTree └── reason-cli@3.1.0-linux
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add reason-cli@3.1.0-linux
19 silly decomposeActions action count 8
20 silly decomposeActions fetch reason-cli@3.1.0-linux
21 silly decomposeActions extract reason-cli@3.1.0-linux
22 silly decomposeActions preinstall reason-cli@3.1.0-linux
23 silly decomposeActions build reason-cli@3.1.0-linux
24 silly decomposeActions install reason-cli@3.1.0-linux
25 silly decomposeActions postinstall reason-cli@3.1.0-linux
26 silly decomposeActions finalize reason-cli@3.1.0-linux
27 silly decomposeActions refresh-package-json reason-cli@3.1.0-linux
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
31 verbose lock using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
32 silly doParallel extract 1
33 silly extract reason-cli@3.1.0-linux
34 silly tarball trying reason-cli@3.1.0-linux by hash: sha1-GxR73hi4VKwl+n9sjxYlKzktjqU=
35 silly extract reason-cli@3.1.0-linux extracted to /usr/lib/node_modules/.staging/reason-cli-8aad2fd0 (1464ms)
36 silly doReverseSerial unbuild 8
37 silly doSerial remove 8
38 silly doSerial move 8
39 silly doSerial finalize 8
40 silly finalize /usr/lib64/node_modules/reason-cli
41 silly doParallel refresh-package-json 1
42 silly refresh-package-json /usr/lib64/node_modules/reason-cli
43 silly doParallel preinstall 1
44 silly preinstall reason-cli@3.1.0-linux
45 info lifecycle reason-cli@3.1.0-linux~preinstall: reason-cli@3.1.0-linux
46 silly doSerial build 8
47 silly build reason-cli@3.1.0-linux
48 info linkStuff reason-cli@3.1.0-linux
49 silly linkStuff reason-cli@3.1.0-linux has /usr/lib/node_modules as its parent node_modules
50 silly linkStuff reason-cli@3.1.0-linux is part of a global install
51 silly linkStuff reason-cli@3.1.0-linux is installed into a global node_modules
52 silly linkStuff reason-cli@3.1.0-linux is installed into the top-level global node_modules
53 verbose linkBins reason-cli@3.1.0-linux
54 verbose linkBins [ { ocamlmerlin: '.bin/ocamlmerlin',
54 verbose linkBins     'ocamlmerlin-reason': '.bin/ocamlmerlin-reason',
54 verbose linkBins     rtop: '.bin/rtop',
54 verbose linkBins     utop: '.bin/utop',
54 verbose linkBins     refmt: '.bin/refmt',
54 verbose linkBins     refmttype: '.bin/refmttype',
54 verbose linkBins     reopt: '.bin/reopt',
54 verbose linkBins     rebuild: '.bin/rebuild',
54 verbose linkBins     reactjs_jsx_ppx_v2: '.bin/reactjs_jsx_ppx_v2',
54 verbose linkBins     reactjs_jsx_ppx_v3: '.bin/reactjs_jsx_ppx_v3',
54 verbose linkBins     'reason-cli-esy-sandbox': '.bin/reason-cli-esy-sandbox' },
54 verbose linkBins   '/usr/bin',
54 verbose linkBins   true ]
55 verbose linkMans reason-cli@3.1.0-linux
56 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/ocamlmerlin
57 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/rtop
58 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/utop
59 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/ocamlmerlin-reason
60 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/refmt
61 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/refmttype
62 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/reopt
63 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/rebuild
64 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_v2
65 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_v3
66 silly linkBins Converting line endings of hashbang file: /usr/lib/node_modules/reason-cli/.bin/reason-cli-esy-sandbox
67 silly doSerial global-link 8
68 silly doParallel update-linked 0
69 silly doSerial install 8
70 silly install reason-cli@3.1.0-linux
71 info lifecycle reason-cli@3.1.0-linux~install: reason-cli@3.1.0-linux
72 silly doSerial postinstall 8
73 silly postinstall reason-cli@3.1.0-linux
74 info lifecycle reason-cli@3.1.0-linux~postinstall: reason-cli@3.1.0-linux
75 verbose lifecycle reason-cli@3.1.0-linux~postinstall: unsafe-perm in lifecycle false
76 verbose lifecycle reason-cli@3.1.0-linux~postinstall: PATH: /usr/lib64/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/reason-cli/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/sbin:/usr/bin:/sbin:/bin
77 verbose lifecycle reason-cli@3.1.0-linux~postinstall: CWD: /usr/lib/node_modules/reason-cli
78 silly lifecycle reason-cli@3.1.0-linux~postinstall: Args: [ '-c', './bin/esyBuildRelease bin install' ]
79 silly lifecycle reason-cli@3.1.0-linux~postinstall: Returned: code: 2  signal: null
80 info lifecycle reason-cli@3.1.0-linux~postinstall: Failed to exec postinstall script
81 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
82 verbose stack Error: reason-cli@3.1.0-linux postinstall: `./bin/esyBuildRelease bin install`
82 verbose stack Exit status 2
82 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
82 verbose stack     at emitTwo (events.js:126:13)
82 verbose stack     at EventEmitter.emit (events.js:214:7)
82 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
82 verbose stack     at emitTwo (events.js:126:13)
82 verbose stack     at ChildProcess.emit (events.js:214:7)
82 verbose stack     at maybeClose (internal/child_process.js:925:16)
82 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
83 verbose pkgid reason-cli@3.1.0-linux
84 verbose cwd /home/kfish
85 verbose Linux 4.15.6-58.current
86 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "reason-cli@3.1.0-linux"
87 verbose node v8.11.0
88 verbose npm  v5.8.0
89 error code ELIFECYCLE
90 error errno 2
91 error reason-cli@3.1.0-linux postinstall: `./bin/esyBuildRelease bin install`
91 error Exit status 2
92 error Failed at the reason-cli@3.1.0-linux postinstall script.
92 error This is probably not a problem with npm. There is likely additional logging output above.
93 verbose exit [ 2, true ]
```
Does anyone know a fix to this?

On Solus 3.999

uname -a: `Linux klaptop 4.15.6-58.current #1 SMP PREEMPT Mon Feb 26 09:52:41 UTC 2018 x86_64 GNU/Linux`

**Comment by kfish610** [comment]
https://github.com/reasonml/reasonml.github.io/pull/157 fixes this
