### ISSUE TITLE
bsb periodically fails to generated JS files saved with VIM

### ISSUE THREAD

**Issue by brightpuddle** [facebook/reason#1939]
While editing files, sometimes bsb will delete the destination .bs.js file. Typically, saving the .re file again will regenerate the .bs.js file. This causes significant problems with upstream tools, e.g. webpack-dev-middleware/hot-middleware fails, emits lots of errors, and forces a live reload.

It seems to happen more easily/consistently on a larger project with more files and dependencies, but I can reproduce it directly from the basic-reason and react templates with *a lot* of repeated saves.

### Steps to reproduce

Standard project init:

1. `bsb -init blah -theme basic-reason`
2. `cd blah &&  yarn start`

In another terminal:

`nodemon ./src/Demo.bs.js`

In the editor, save Demo.re repeatedly. It takes *a lot* of saves for this to happen, but I can reproduce it in any project. Happens almost immediately if the saves are performed quickly, but it also happens with normal editing, so doesn't seem to purely a rate issue.

### BSB output

The last build is the one that failed.

```>>>> Start compiling
Rebuilding since [ [ 'rename', 'Index.re' ], [ 'rename', 'Index.re~' ] ]
ninja: Entering directory `lib/bs'
ninja: no work to do.
>>>> Finish compiling
>>>> Start compiling
Rebuilding since [ [ 'rename', 'Index.re' ], [ 'rename', 'Index.re~' ] ]
ninja: Entering directory `lib/bs'
ninja: no work to do.
>>>> Finish compiling
>>>> Start compiling
Rebuilding since [ [ 'rename', '4913' ] ]
ninja: Entering directory `lib/bs'
[2/2] Building src/Index.mlast.d
[1/1] Building src/Index-ReactTemplate.cmj
>>>> Finish compiling
>>>> Start compiling
Rebuilding since [ [ 'rename', 'Index.re' ],
  [ 'rename', 'Index.re~' ],
  [ 'rename', 'Index.re' ],
  [ 'rename', 'Index.re~' ] ]
ninja: Entering directory `lib/bs'
ninja: no work to do.
>>>> Finish compiling

```

### Nodemon output

```[nodemon] starting node src/Index.bs.js
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/nathan/src/test/reason/blah/src/Index.bs.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
[nodemon] app crashed - waiting for file changes before starting...
```

### System details:

MacOS 10.13.4 (High Sierra)
Editor: neovim
bs-platform v3.0.0
Node: 8.11.1

**Comment by brightpuddle** [comment]
More detail...

I can't reproduce this in VSC or Sublime, so it may be related to how Vim saves files. Vim writes to a temp file and then renames over the original, which registers to bsb as "rename" instead of "change." This *appears* to cause intermittent issues with bsb. Not 100% sure of this since it's only intermittent.

Possibly relevant:

https://github.com/neovim/neovim/issues/1380

**Comment by brightpuddle** [comment]
Duplicate:

https://github.com/BuckleScript/bucklescript/issues/1675
https://github.com/BuckleScript/bucklescript/issues/2744

For anybody that stumbles on this the fix for both vim and emacs is in the first link, i.e. `set backupcopy=yes` in .vimrc or `(setq create-lockfiles nil)` for emacs.
